### ISSUE TITLE
Dedicated PeerDB Instance

### ISSUE THREAD

**Issue by jordangarside** [peerlibrary/meteor-peerdb#38]
I'm a little confused about this section of the documentation:

> ### PEERDB_INSTANCES=1

> As your application grows you might want to run specialized Meteor instances just to do PeerDB reactive MongoDB queries. To distribute PeerDB load, configure the number of PeerDB instances using the PEERDB_INSTANCES environment variable. Suggested setting is that your web-facing instances disable PeerDB by setting PEERDB_INSTANCES to 0, and then you have dedicated PeerDB instances.

A few questions...

So it's recommended to setup a separate meteor instance running PeerDB to handle relations?

What happens if you try to do an insert from the server of a public facing meteor project connected to the Mongo database that fails on the separate PeerDB server due to validation? Does it fail on the public facing meteor instance without PeerDB?
I imagine the errors on the PeerDB server can't propagate down to the Meteor server through Mongo (so I must be thinking about something incorrectly).

How does PeerDB manage the collection hooks? Will everything work correctly if the insert/update/deletes aren't done from the meteor server with PeerDB?

My use case is that I have several Meteor servers connected to the same Compose instance, but they all need the same logic taken into account should they try to do an invalid insert/update, and also need the relations managed. Currently I'm doing this by packaging all the database logic (collection-hooks/observers/schemas) in a package and then importing that for every meteor project.
Hoping this is much simpler than that! :)

**Comment by mitar** [comment]
> So it's recommended to setup a separate meteor instance running PeerDB to handle relations?

Yes, just so that your user facing instances and not slowed down because of the PeerDB work.

> What happens if you try to do an insert from the server of a public facing meteor project connected to the Mongo database that fails on the separate PeerDB server due to validation? Does it fail on the public facing meteor instance without PeerDB?

PeerDB does not handle validation. It will warn you if it detects something strange, but is not preventing any writes or anything. If you want to do validation, do that before you write to the database.

Frankly, I never needed validation at the database level. Just make your queries correct and test things before deployment. :-)

BTW, MongoDB 3.0 has native validation support. Maybe look into that.

> I imagine the errors on the PeerDB server can't propagate down to the Meteor server through Mongo (so I must be thinking about something incorrectly).

They do not propagate even when you are running only one instance, web instance together with PeerDB. PeerDB is asynchronous, it processes changes independently from the changes themselves. The idea is that you have eventually consistency. So you want a fast write which quickly returns (you should make sure that write is correct). And then once you make this change PeerDB will in the background propagate changes to all related documents, if you have defined any relations. Eventually they will all be updated.

> How does PeerDB manage the collection hooks? Will everything work correctly if the insert/update/deletes aren't done from the meteor server with PeerDB?

PeerDB does not use collection hooks but it observes collections. So yea, changes can come to the database from anywhere, Meteor or even outside. The beauty of oplog.

> but they all need the same logic taken into account should they try to do an invalid insert/update

For that you should use SimpleSchema or something like that. Or just verify manually. PeerDB does not validate or reject invalid inserts/updates. Frankly, I believe I see such code as simply buggy. If you release a buggy code which made problematic changes then I think it is better than just to fail validation (which might even make things worse) is to look at what exactly is going wrong and then fix data using a [migration](https://github.com/peerlibrary/meteor-peerdb-migrations).

> also need the relations managed.

That part is what PeerDB takes care of. You define relations declaratively and then the rest is taken care for you.

**Comment by jordangarside** [comment]
Thanks a lot @mitar!

I have just one more question please:

> The idea is that you have eventually consistency. So you want a fast write which quickly returns (you should make sure that write is correct).

So I need to insert the document with the referenced document if I want to do an immediate insert then read?

I can't do something like:

```
postId = Posts.insert
  text: "blah"
  author:
    _id: "ABC123"

post = Posts.findOne(postId)
authorName = post.author.name #This won't be available correct?
```
?

**Comment by mitar** [comment]
It will not be available immediately, but if you do your query in a reactive context it will be available eventually. So all depends on your use case and how your particular code expects existence of values or can it handle lack of values in sub-documents.

The pattern which I currently use the most is that I do things like:

````
postId = Posts.insert
  text: "blah"
  author: _.pick(author, '_id', 'name')
```

So it turns out that often you anyway already have at least some version of the reference object around (you need `_id` anyway). So you can populate it yourself initially, and then you can make sure that PeerDB will assure data is recent.

Sometimes I even make a method on the `Author` class:

````
postId = Posts.insert
  text: "blah"
  author: author.getReference()
```

You are right that probably some of this could be automatized. For example, that you could just do:

````
postId = Posts.insert
  text: "blah"
  author: author
```

And it would automatically take only the fields you defined in the `ReferenceField`. **But do not do it now.** Currently the whole object would be stored and nobody would clear out the extra fields.

**Comment by jordangarside** [comment]
Gotcha, thanks a ton @mitar !

**Comment by jordangarside** [comment]
@mitar
Hey, I had another question when you have multiple dedicated PeerDB instances.
Will triggers for the same events be run on all dedicated PeerDB instances?
So, the example for triggers on the readme has the updatedAt field updated by a trigger, does this trigger fire on PEERDB_INSTANCE 0 and 1?

Also, it seems like peerdb triggers aren't a great solution if the data consistency is important due to the fact that if you update the dedicated peerdb instance with mup, you would have to take down every web-facing server to ensure no writes happen while peerdb is down. Am I correct on this?

Thanks again,
Jordan
